language: python

python:
    - "3.6"
    - "3.7"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov

install:
  - pip install -e .

script: pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
